version: '2'
services:
  # nginx:
  #   image: nginx:stable-alpine
  #   volumes:
  #     - ./proxy.conf:/etc/nginx/conf.d/default.conf
  #     - ./ssl:/etc/nginx/ssl
  #   ports:
  #     - 8080:80
  #     - 443:443
  #   extra_hosts:
  #     - "dockerhost:192.168.1.78"
  web:
    build: .
    environment:
      APP_USERNAME: admin
      APP_PASSWORD: admin
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: releaseserver
      DB_NAME: releaseserver
      DB_PASSWORD: secret
      TOKEN_SECRET: change_me_in_production
      APP_URL: 'http://192.168.1.78:5000'
    depends_on:
      - db
    ports:
      - '5000:5000'
    volumes:
      - .:/usr/src/electron-release-server
    entrypoint: ./scripts/wait.sh db:5432 -- npm start
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: releaseserver
